# Generated by Django 4.2.6 on 2023-11-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedtask',
            name='shared_at',
        ),
    ]
