# Generated by Django 4.2.6 on 2023-10-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedtask',
            old_name='patricipants',
            new_name='participants',
        ),
    ]
