name: Django Test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Set manage.py path
      id: manage_py_path
      run: |
        if [ $RUNNER_OS == "Linux" ]; then
          echo "::set-output name=manage_py_path::./django_task_management/manage.py"
        elif [ $RUNNER_OS == "Windows" ]; then
          echo "::set-output name=manage_py_path::.\django_task_management\manage.py"
        fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python ${{ steps.manage_py_path.outputs.manage_py_path }} test
